config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  post "/graphiql", to: "graphql#execute"
  # resources :players, only: [:index, :show, :create, :update]
  resources :players
  resources :clubs
  resources :federations

  #peticion GET /index al controlador health, metodo health
  get '/login', to: 'auth#login'
  get '/health', to: 'health#health'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/club.rb
class Club < ApplicationRecord
  belongs_to :federation
  has_many :players

  validates :name, presence: true
  validates :foundation_date, presence: true
  validates :federation_id, presence: true
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :set_club, only: %i[ show edit update destroy ]

  # GET /clubs or /clubs.json
  def index
    @clubs = Club.all
  end

  # GET /clubs/1 or /clubs/1.json
  def show
  end

  # GET /clubs/new
  def new
    @club = Club.new
  end

  # GET /clubs/1/edit
  def edit
  end

  # POST /clubs or /clubs.json
  def create
    @club = Club.new(club_params)

    respond_to do |format|
      if @club.save
        format.html { redirect_to club_url(@club), notice: "Club was successfully created." }
        format.json { render :show, status: :created, location: @club }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clubs/1 or /clubs/1.json
  def update
    respond_to do |format|
      if @club.update(club_params)
        format.html { redirect_to club_url(@club), notice: "Club was successfully updated." }
        format.json { render :show, status: :ok, location: @club }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clubs/1 or /clubs/1.json
  def destroy
    @club.destroy

    respond_to do |format|
      format.html { redirect_to clubs_url, notice: "Club was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_club
      @club = Club.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def club_params
      params.require(:club).permit(:name, :foundation_date, :federation_id)
    end
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/views/clubs/_club.html.erb
<div id="<%= dom_id club %>">
  <p>
    <strong>Name:</strong>
    <%= club.name %>
  </p>

  <p>
    <strong>Foundation date:</strong>
    <%= club.foundation_date %>
  </p>

  <p>
    <strong>Federation:</strong>
    <%= club.federation_id %>
  </p>

</div>

app/views/clubs/_form.html.erb
<%= form_with(model: club) do |form| %>
  <% if club.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(club.errors.count, "error") %> prohibited this club from being saved:</h2>

      <ul>
        <% club.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_area :name %>
  </div>

  <div>
    <%= form.label :foundation_date, style: "display: block" %>
    <%= form.date_field :foundation_date %>
  </div>

  <div>
    <%= form.label :federation_id, style: "display: block" %>
    <%= form.text_field :federation_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/clubs/edit.html.erb
<h1>Editing club</h1>

<%= render "form", club: @club %>

<br>

<div>
  <%= link_to "Show this club", @club %> |
  <%= link_to "Back to clubs", clubs_path %>
</div>

app/views/clubs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clubs</h1>
<table id='ordersTable' class='table table-striped table-sm'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Foundation date</th>
      <th>Federation</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

<section id="simple">
  <h2>Simple Example</h2>
  <div class="row">
    <div class="span6">
      <h3>Without Select2</h3>
      <form>
        <%= select_tag "clubs", options_from_collection_for_select(@clubs, "id", "name") %>
      </form>

    </div>
    <div class="span6">
      <h3>With Select2</h3>
      <form>
        <%= select_tag "clubs", options_from_collection_for_select(@clubs, "id", "name"), id: "js-example-basic-multiple" %>
      </form>
    </div>
  </div>
</section>

  <tbody>
    <% @clubs.each do |club| %>
      <tr>
        <td><%= club.name %></td>
        <td><%= club.foundation_date %></td>
        <td><%= club.federation.name %></td>
        <td><%= link_to 'Show', club %></td>
        <td><%= link_to 'Edit', edit_club_path(club) %></td>
        <td><%= link_to 'Destroy', club, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New club', new_club_path %>

<%# <script src="https://code.jquery.com/jquery-3.3.1.js"></script> %>
<%# <script>
  $(document).ready(function() {
    var oTable = $("#ordersTable").DataTable({})
  });
</script> %>

<% content_for :js do %>
  <script type="text/javascript">
  $(document).ready(function() {
    $('select#js-example-basic-multiple').select2();
  });
  </script>
<% end %>

app/views/clubs/new.html.erb
<h1>New club</h1>

<%= render "form", club: @club %>

<br>

<div>
  <%= link_to "Back to clubs", clubs_path %>
</div>

app/views/clubs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @club %>

<div>
  <%= link_to "Edit this club", edit_club_path(@club) %> |
  <%= link_to "Back to clubs", clubs_path %>

  <%= button_to "Destroy this club", @club, method: :delete %>
</div>