config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  post "/graphiql", to: "graphql#execute"
  # resources :players, only: [:index, :show, :create, :update]
  resources :players
  resources :clubs
  resources :federations

  #peticion GET /index al controlador health, metodo health
  get '/login', to: 'auth#login'
  get '/health', to: 'health#health'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/federation.rb
class Federation < ApplicationRecord
  has_many :clubs

  validates :name, presence: true
  validates :foundation_date, presence: true
end

app/controllers/federations_controller.rb
class FederationsController < ApplicationController

  rescue_from Exception do |e|
    render json: { error: e.message }, status: :internal_server_error
  end

  rescue_from ActiveRecord::RecordInvalid do |e|
    render json: { error: e.message }, status: :unprocessable_entity
  end

  before_action :set_federation, only: %i[ show edit update destroy ]

  # GET /federations or /federations.json
  def index
    @federations = Federation.all
    if !params[:search].nil? && params[:search].present?
      @federations = FederationsSearchService.search(@federations, params[:search])
    end
    render json: @federations, status: :ok
  end

  # GET /federations/1 or /federations/1.json
  def show
    @federation = Federation.find(params[:id])
    render json: @federation, status: :ok
  end

  # GET /federations/new
  def new
    @federation = Federation.new
  end

  # GET /federations/1/edit
  def edit
  end

  # POST /federations or /federations.json
  # def create
  #   @federation = Federation.new(federation_params)

  #   respond_to do |format|
  #     if @federation.save
  #       format.html { redirect_to federation_url(@federation), notice: "Federation was successfully created." }
  #       format.json { render :show, status: :created, location: @federation }
  #     else
  #       format.html { render :new, status: :unprocessable_entity }
  #       format.json { render json: @federation.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  def create
    @federation = Federation.create!(create_params)
    render json: @federation, status: :created
  end

  # PATCH/PUT /federations/1 or /federations/1.json
  # def update
  #   respond_to do |format|
  #     if @federation.update(federation_params)
  #       format.html { redirect_to federation_url(@federation), notice: "Federation was successfully updated." }
  #       format.json { render :show, status: :ok, location: @federation }
  #     else
  #       format.html { render :edit, status: :unprocessable_entity }
  #       format.json { render json: @federation.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  def update
    @federation = Federation.find(params[:id])
    @federation.update!(update_params)
    render json: @federation, status: :ok
  end

  # DELETE /federations/1 or /federations/1.json
  def destroy
    @federation.destroy

    respond_to do |format|
      format.html { redirect_to federations_url, notice: "Federation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_federation
      @federation = Federation.find(params[:id])
    end

    def create_params
      params.require(:federation).permit(:name, :foundation_date)
    end

    # Only allow a list of trusted parameters through.
    def update_params
      params.require(:federation).permit(:name, :foundation_date)
    end
end

app/helpers/federations_helper.rb
module FederationsHelper
end

app/views/federations/_federation.html.erb
<div id="<%= dom_id federation %>">
  <p>
    <strong>Name:</strong>
    <%= federation.name %>
  </p>

  <p>
    <strong>Foundation date:</strong>
    <%= federation.foundation_date %>
  </p>

</div>

app/views/federations/_form.html.erb
<%= form_with(model: federation) do |form| %>
  <% if federation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(federation.errors.count, "error") %> prohibited this federation from being saved:</h2>

      <ul>
        <% federation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_area :name %>
  </div>

  <div>
    <%= form.label :foundation_date, style: "display: block" %>
    <%= form.date_field :foundation_date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/federations/edit.html.erb
<h1>Editing federation</h1>

<%= render "form", federation: @federation %>

<br>

<div>
  <%= link_to "Show this federation", @federation %> |
  <%= link_to "Back to federations", federations_path %>
</div>

app/views/federations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Federations</h1>

<div id="federations">
  <% @federations.each do |federation| %>
    <%= render federation %>
    <p>
      <%= link_to "Show this federation", federation %>
    </p>
  <% end %>
</div>

<%= link_to "New federation", new_federation_path %>

app/views/federations/new.html.erb
<h1>New federation</h1>

<%= render "form", federation: @federation %>

<br>

<div>
  <%= link_to "Back to federations", federations_path %>
</div>

app/views/federations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @federation %>

<div>
  <%= link_to "Edit this federation", edit_federation_path(@federation) %> |
  <%= link_to "Back to federations", federations_path %>

  <%= button_to "Destroy this federation", @federation, method: :delete %>
</div>